language: android

android:
  components:
    - platform-tools
    - tools
    - build-tools-23.0.3
    - android-23
    - extra-android-support
    - extra-android-m2repository
    - extra-google-m2repository
    - sys-img-armeabi-v7a-android-23

before_install:
  # install ruby
  - rvm install 2.3.1
  # install calabash-android
  - gem install calabash-android

before_script:
  - echo no | android create avd --force --name test --target android-23 --abi armeabi-v7a
  - emulator -avd test -no-skin -no-audio -no-window -no-boot-anim &
  - android-wait-for-emulator
  - sleep 10 # give screen some time to become unlocked

script:
  - adb kill-server
  - adb start-server
  - adb devices
  - adb install -r chat.apk
#  - calabash-android resign chat.apk
  - calabash-android run chat.apk features/channel.feature
